### ISSUE TITLE
Code analyses still coded as 'CHECK'

### ISSUE THREAD

**Issue by egouldo** [egouldo/ManyEcoEvo#43]
Hi Hannah or @parkerth,

Could you please check the master_data file (at `"data-raw/anonymised_data/master_data.csv"`) and code as necessary or mark as NA if can't resolve? there are a few analyses remaining with values 'CHECK':

|response_id       | submission_id| analysis_id| split_id|test_variable               |Bayesian |linear_model |model_subclass |exclusions_effect_analysis |Conclusion |data_cleaning_preprocessing_tool |data_cleaning_preprocessing_version |data_analysis_tool |data_analysis_version |
|:-----------------|-------------:|-----------:|--------:|:---------------------------|:--------|:------------|:--------------|:--------------------------|:----------|:--------------------------------|:-----------------------------------|:------------------|:---------------------|
|R_11787O3NmejXKAH |             1|           2|        2|net_rearing_manipulation    |0        |generalised  |standard       |exclude_all                |CHECK      |R                                |NA                                  |R                  |NA                    |
|R_11787O3NmejXKAH |             1|           2|        3|net_rearing_manipulation    |0        |generalised  |standard       |exclude_all                |CHECK      |R                                |NA                                  |R                  |NA                    |
|R_11787O3NmejXKAH |             1|           2|        1|net_rearing_manipulation    |0        |generalised  |standard       |exclude_all                |CHECK      |R                                |NA                                  |R                  |NA                    |
|R_1eXlFKlQdiD2F59 |             2|           2|        1|rear_Cs_at_start_of_rearing |0        |linear       |standard       |retain                     |CHECK      |CHECK                            |CHECK                               |CHECK              |CHECK                 |
|R_1GJlffAgZv6SY4y |             1|           1|        1|NA                          |CHECK    |CHECK        |standard       |exclude_all                |none_c     |R                                |4.0.0                               |R                  |4.0.0                 |
|R_1M0cMZL2IPYWHoi |             1|           1|        1|NA                          |CHECK    |CHECK        |CHECK          |exclude_all                |CHECK      |CHECK                            |CHECK                               |CHECK              |CHECK                 |
|R_1M0cMZL2IPYWHoi |             1|           1|        1|NA                          |1        |generalised  |CHECK          |exclude_all                |NA         |R                                |3.6.3                               |R                  |3.6.3                 |
|R_1QlnXdW5tKuUQIr |             1|           1|        1|CHECK                       |CHECK    |CHECK        |CHECK          |CHECK                      |neg_q      |R                                |3.6.1                               |R                  |3.6.1                 |
|R_21gmMa0uclrNoTP |             2|           1|        1|NA                          |CHECK    |linear       |CHECK          |exclude_all                |CHECK      |CHECK                            |CHECK                               |CHECK              |CHECK                 |
|R_2Pjoz1X4q5XRClO |             2|           1|        1|NA                          |CHECK    |CHECK        |standard       |exclude_all                |CHECK      |CHECK                            |CHECK                               |CHECK              |CHECK                 |
|R_2zNKAmJcWbM4QtY |             1|           1|        1|NA                          |0        |CHECK        |standard       |retain                     |none_q     |R                                |3.6.1                               |R                  |3.6.1                 |
|R_3EbbZxcQ3gctVZu |             1|           1|        1|NA                          |0        |CHECK        |hurdle         |exclude_all                |neg_q      |R                                |3.6.1                               |R                  |3.6.1                 |
|R_3Kvy0h01LXHWniT |             2|           2|        1|NA                          |0        |generalised  |standard       |retain                     |CHECK      |R                                |NA                                  |R                  |NA                    |
|R_3nBCE4hMLh5s3qt |             3|           1|        2|NA                          |CHECK    |CHECK        |standard       |NA                         |CHECK      |CHECK                            |CHECK                               |CHECK              |CHECK                 |
|R_3nBCE4hMLh5s3qt |             3|           1|        1|NA                          |CHECK    |CHECK        |standard       |NA                         |CHECK      |CHECK                            |CHECK                               |CHECK              |CHECK                 |
|R_AzL6RdNTHtPjxzX |             1|           1|        2|NA                          |CHECK    |CHECK        |standard       |exclude_all                |CHECK      |CHECK                            |CHECK                               |CHECK              |CHECK                 |
|R_es2jrrN9CTGwl5D |             1|           1|        1|NA                          |CHECK    |CHECK        |CHECK          |exclude_all                |neg_q      |R                                |4.0.0                               |R                  |4.0.0                 |

**Comment by parkerth** [comment]
not sure what to do here. The rows with "CHECK" in the Bayesian and/or linear_model column are all 'exclude' (or in one case, 'check.mixed.team'). 
I guess I will go ahead and change them to NA, but it seems like there might be a bigger problem with the code if this matters. Is the 'exclude' code working?

**Comment by parkerth** [comment]
... also true for 'model_subclass' variable (all checks are also exclusions)

**Comment by parkerth** [comment]
... also true for these columns:

**Comment by parkerth** [comment]
That file is now on branch(?) with a pull request(?)  (if my use of jargon is correct)

**Comment by hannahsfraser** [comment]
Awesome stuff Tim. You're fast like a fox!

**Comment by egouldo** [comment]
Thanks Tim, all while I was sleeping.

So that’s not the source of the bug I haven’t yet solved, but I was doing some processing on the full dataset before exclusion.

That being said, I will check for instances where the exclusions haven’t been applied where they should be.

Elliot.

Sent from my iPhone

On 18 Jun 2024, at 12:42 AM, Hannah Fraser ***@***.***> wrote:

﻿

Awesome stuff Tim. You're fast like a fox!

**Comment by parkerth** [comment]
That makes sense.  Where do we stand at this point?

**Comment by egouldo** [comment]
Note that Capella-1-1-1 was marked as CHECK.mixed.team for `exclusions_all`. which was replaced with NA.mixed.team, and then I just did a replacement with NA across multiple columns for this entry in prev. commit, b00d31f. But that probably means we should check whether we want to include it at all @parkerth ?

**Comment by egouldo** [comment]
Looks like has been fixed, row has been marked as 'exclude' and 'exclude_all' under relevant exclusion columns.
