### ISSUE TITLE
Duplicate entry for `R_1LRQQ2WHQAENTM_1-1-1` in Forest Plot specification curve

### ISSUE THREAD

**Issue by egouldo** [egouldo/ManyEcoEvo#81]
This study ID has two entries...

- response variable: `euc_sdlngs0_50cm`
- response_variable: `euc_sdlngs50cm_2m`

But if this is the case, they should have two different study id's! Investigate source of error and fix.

**Comment by parkerth** [comment]
There does not seem to be a problem.  Here is what i see:
Boorowa-eucalyptus-1-3-1   euc_sdlgs>2m
Boorowa-eucalyptus-1-1-1   euc_sdlgs0_50cm
Boorowa-eucalyptus-1-2-1   euc_sdlgs50cm_2m
